### ISSUE TITLE
Bugs while creating QRCode

### ISSUE THREAD

**Issue by lorimmar** [Shane32/QRCoder#1]
Hi Raffael
I use your library for printing QRCode on documents. Some of the codes are generated incorrectly. I give a few examples, and the parameters and values ​​with which they were noticed.
Encoded string: PA 9486/AMG/2014
ECC Level: M
Decoded as: PA 94870AMG/2014

Encoded string: PA 9490/AMG/2014
ECC Level: M
Decoded as: PA 949CFAMG/2014

Encoded string: PA 9491/AMG/2014
ECC Level: M
Decoded as: PA 949DFAMG/2014

**Comment by codebude** [comment]
There was an error in the CalculateECCWords-method. I forgot to remove the leading coefficients from the message polynoms if they are zero. It's fixed with Commit https://github.com/codebude/QRCoder/commit/8103f030ec3ce8983051b6a74dde5822d1c71103
