### ISSUE TITLE
In Linux system, which class do I use to generate QR codes with iocn?

### ISSUE THREAD

**Issue by yb12306** [Shane32/QRCoder#573]
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement

**Comment by codebude** [comment]
The rendering classes that work under Linux are listed in the compatibility matrix in our wiki:
https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#2-overview-of-the-different-renderers

Out of those only the SvgQRCode supports icons out of the box. 

But you could use any of the other Linux compatible renderers and then just take a image manipulation/drawing library of your choice to paint a logo onto the generated code.
