### ISSUE TITLE
How to get QR bytes in Blazor app .NET8?

### ISSUE THREAD

**Issue by hovek** [Shane32/QRCoder#574]
In non-windows .NET8 project "new QRCode()" has an empty constructor. How to get QR bytes from a string? 
I've looked at .NET5 Blazor example but it's outdated, does not work in .NET8.

**Comment by hovek** [comment]
This might be it:

`            var qRCodeGenerator = new QRCodeGenerator();
            var qRCodeData = qRCodeGenerator.CreateQrCode(text, QRCodeGenerator.ECCLevel.Q);
            var qRCode = new BitmapByteQRCode(qRCodeData);
            var bytes = qRCode.GetGraphic(5);`

**Comment by codebude** [comment]
Alternatively you could use the PNG renderer:

```csharp
using (QRCodeGenerator qrGenerator = new QRCodeGenerator())
using (QRCodeData qrCodeData = qrGenerator.CreateQrCode("The text which should be encoded.", QRCodeGenerator.ECCLevel.Q))
using (PngByteQRCode qrCode = new PngByteQRCode(qrCodeData))
{
    byte[] qrCodeImage = qrCode.GetGraphic(20);
}
```

In addition check the compatibility matrix. Every renderer listed in the "Net 6.0" column should work in your .NET8 environment: https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#2-overview-of-the-different-renderers
